import type { SecurityGrade } from "./grade.js";
import type { Tool } from "./lint.js";
import { badgeUrl, type CertResult } from "./score.js";
import type { RiskFinding } from "./security.js";
import type { DoctorResult } from "./types.js";

export interface ReportInput {
  target: string;
  result: DoctorResult;
  cert: CertResult;
  tools: Tool[];
  risks: RiskFinding[];
}

/** A full, shareable Markdown certification report — pure, deterministic. */
export function certificationMarkdown(input: ReportInput): string {
  const { target, result, cert, tools, risks } = input;
  const lines: string[] = [];

  lines.push("# MCP Cert Report", "");
  lines.push(`![MCP Cert](${badgeUrl(cert)})`, "");
  lines.push(`**Target:** \`${target}\`  `);
  lines.push(`**Score:** ${cert.score}/100 (${cert.grade}) — ${cert.certified ? "✅ Certified" : "❌ Not certified"}  `);
  lines.push(`**Generated:** ${result.startedAt}`, "");

  if (cert.breakdown) lines.push(...gradeSection(cert.breakdown));

  lines.push("## Checks", "");
  lines.push("| Check | Result | Detail |", "| --- | --- | --- |");
  for (const c of result.checks) {
    const icon = c.severity === "pass" ? "✅" : c.severity === "warn" ? "⚠️" : c.severity === "fail" ? "❌" : "ℹ️";
    lines.push(`| ${esc(c.title)} | ${icon} ${c.severity} | ${esc(c.detail)} |`);
  }
  lines.push("");

  lines.push(`## Tools (${tools.length})`, "");
  for (const t of tools) {
    const first = (t.description ?? "").split("\n")[0] || "_no description_";
    lines.push(`- \`${t.name}\` — ${esc(first)}`);
  }
  lines.push("");

  lines.push("## Capability risk", "");
  if (risks.length === 0) {
    lines.push("No elevated-capability tools detected.");
  } else {
    lines.push("| Tool | Risk | Why |", "| --- | --- | --- |");
    for (const r of risks) lines.push(`| \`${r.tool}\` | ${r.risk} | ${esc(r.reason)} |`);
  }
  lines.push("");

  lines.push("---", "_Generated by [mcpcert](https://www.npmjs.com/package/mcpcert) — deterministic, no LLM._", "");
  return lines.join("\n");
}

function gradeSection(g: SecurityGrade): string[] {
  const lines: string[] = ["## Security grade", ""];
  lines.push(`Rubric \`${g.rubric}\` · probed: ${g.assessed.probe ? "yes" : "no (conformance only)"}`, "");
  lines.push("| Dimension | Score | Weight | Findings |", "| --- | --- | --- | --- |");
  for (const d of g.dimensions) {
    if (!d.assessed) {
      lines.push(`| ${d.title} | _not assessed_ | — | run \`mcpcert probe\` |`);
    } else {
      lines.push(`| ${d.title} | ${d.score}/100 | ${Math.round(d.weight * 100)}% | ${d.deductions.length} |`);
    }
  }
  lines.push("");

  if (g.caps.length > 0) {
    lines.push("**Capped** (one serious issue dominates the grade):", "");
    for (const c of g.caps) lines.push(`- ⛔ capped at ${c.ceiling}/100 — ${esc(c.reason)}`);
    lines.push("");
  }

  const hard = g.dimensions.flatMap((d) => d.deductions).filter((x) => x.severity === "critical" || x.severity === "high");
  if (hard.length > 0) {
    lines.push("**Top findings:**", "");
    for (const x of hard.slice(0, 12)) lines.push(`- \`${x.severity}\` ${x.tool ? `\`${x.tool}\` — ` : ""}${esc(x.detail)}`);
    lines.push("");
  }
  return lines;
}

function esc(s: string): string {
  return s.replace(/\|/g, "\\|").replace(/\n/g, " ");
}
