import type { Tool } from "./lint.js";
import { badgeUrl, type CertResult } from "./score.js";
import type { RiskFinding } from "./security.js";
import type { DoctorResult } from "./types.js";

export interface ReportInput {
  target: string;
  result: DoctorResult;
  cert: CertResult;
  tools: Tool[];
  risks: RiskFinding[];
}

/** A full, shareable Markdown certification report — pure, deterministic. */
export function certificationMarkdown(input: ReportInput): string {
  const { target, result, cert, tools, risks } = input;
  const lines: string[] = [];

  lines.push("# MCP Cert Report", "");
  lines.push(`![MCP Cert](${badgeUrl(cert)})`, "");
  lines.push(`**Target:** \`${target}\`  `);
  lines.push(`**Score:** ${cert.score}/100 (${cert.grade}) — ${cert.certified ? "✅ Certified" : "❌ Not certified"}  `);
  lines.push(`**Generated:** ${result.startedAt}`, "");

  lines.push("## Checks", "");
  lines.push("| Check | Result | Detail |", "| --- | --- | --- |");
  for (const c of result.checks) {
    const icon = c.severity === "pass" ? "✅" : c.severity === "warn" ? "⚠️" : c.severity === "fail" ? "❌" : "ℹ️";
    lines.push(`| ${esc(c.title)} | ${icon} ${c.severity} | ${esc(c.detail)} |`);
  }
  lines.push("");

  lines.push(`## Tools (${tools.length})`, "");
  for (const t of tools) {
    const first = (t.description ?? "").split("\n")[0] || "_no description_";
    lines.push(`- \`${t.name}\` — ${esc(first)}`);
  }
  lines.push("");

  lines.push("## Capability risk", "");
  if (risks.length === 0) {
    lines.push("No elevated-capability tools detected.");
  } else {
    lines.push("| Tool | Risk | Why |", "| --- | --- | --- |");
    for (const r of risks) lines.push(`| \`${r.tool}\` | ${r.risk} | ${esc(r.reason)} |`);
  }
  lines.push("");

  lines.push("---", "_Generated by [mcpcert](https://www.npmjs.com/package/mcpcert) — deterministic, no LLM._", "");
  return lines.join("\n");
}

function esc(s: string): string {
  return s.replace(/\|/g, "\\|").replace(/\n/g, " ");
}
